### ISSUE TITLE
Repository Name not fitting

### ISSUE THREAD

**Issue by khde** [le-Flow/2.-Semester-Java#1]
This Java Code is for the third semester. The name is irritating.
It should be: 3.-Semester-Java.

**Comment by le-Flow** [comment]
Starting with Java 2 would be stoopid tho

**Comment by khde** [comment]
Can you elaborate?

**Comment by le-Flow** [comment]
> Can you elaborate?

No 😘

**Comment by khde** [comment]
It would just make more sense to name the repository 3.-Semester-Java. or Programming III

**Comment by le-Flow** [comment]
> It would just make more sense to name the repository 3.-Semester-Java. or Programming III

Heresy

**Comment by khde** [comment]
bruh ಠ_ಠ
